apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - name: web
        image: ghcr.io/teyuro/argocd-lab-web:047e77f27dbe795bc3bc6b03001bac3ac8abab5f
        ports:
        - containerPort: 80
