apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - name: web
        image: ghcr.io/teyuro/argocd-lab-web:2f44ccb822f536e0213c47ae92c9731a0051311a
        ports:
        - containerPort: 80
